### ISSUE TITLE
wl-expansion text is not selectable

### ISSUE THREAD

**Issue by Roba1993** [andreasbm/weightless#53] opened 2019-04-17 16:36 UTC
Hi,

first of all thank you for the really great library!

I have a small issue I don't get solved. The text inside the wl-expansion box is not selectable (these blue selection background when hover-clicking over the text).

Is this intended? Or is there a way to fix this?

Thanks,
Robert

**Comment by andreasbm** [comment] 2019-04-27 23:59
Hi Robert!

Thanks a lot for taking your time to open this issue - I am very glad that you like the library. Sorry for not getting back to you before today.

I looked into the issue and found out that it was caused by attaching a shadow root with "delegatesFocus".

```javascript
this.attachShadow({mode: "open", delegatesFocus: true});
```

I assume not being able to select the text is a bug in how shadow roots with "delegatesFocus" is being handled. Since it is an [experimental non-standard feature, only available in Chrome](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/delegatesFocus), I chose to get rid of the functionality in commit 51e26a23d8696762add8910f02818c047e6f969a and published 0.0.33 of Weightless that contains this fix.

I will be closing this issue for now.

Feel free to open more issues if you encounter something unexpected again or have a request for new functionality!

**Closed by andreasbm** 2019-04-27 23:59 UTC
Labels: Browser: Chrome, bug
