### ISSUE TITLE
Ripple stays on most form components

### ISSUE THREAD

**Issue by caliny97** [andreasbm/weightless#60] opened 2019-05-28 21:12 UTC
Ripple stays on most form component (buttons, checkbox, tabs). Looks like the last frames from the animation don't finish.
<img width="75" alt="ripple-checkbox" src="https://user-images.githubusercontent.com/22107640/58512698-ba625100-816b-11e9-9926-c37eb2fccdd2.png">
<img width="112" alt="ripple-tab" src="https://user-images.githubusercontent.com/22107640/58512699-ba625100-816b-11e9-813f-9ddbc71f2793.png">

**Comment by andreasbm** [comment] 2019-05-29 12:57
Thanks a lot for opening this issue 😊This appears to be a duplicate of #56. The focus style is meant to highlight the element that is focused, but is currently shown regardless of whether the user is using pointer or keyboard for navigation. I will close this issue in favor of the other one.

**Closed by andreasbm** 2019-05-29 12:57 UTC
